### ISSUE TITLE
Error: Generating an OpenAPI document using the framework tools

### ISSUE THREAD

**Issue by zonito** [cloudendpoints/endpoints-python#112]
I see below error at the time of generating OpenAPI document

```python
Traceback (most recent call last):
  File "lib/endpoints/endpointscfg.py", line 633, in <module>
    main(sys.argv)
  File "lib/endpoints/endpointscfg.py", line 629, in main
    args.callback(args)
  File "lib/endpoints/endpointscfg.py", line 487, in _GenOpenApiSpecCallback
    application_path=args.application)
  File "lib/endpoints/endpointscfg.py", line 332, in _GenOpenApiSpec
    application_path=application_path)
  File "lib/endpoints/endpointscfg.py", line 183, in GenApiConfig
    module = __import__(module_name, fromlist=base_service_class_name)
  File "/path/to/project/api_handler.py", line 2, in <module>
    import endpoints
  File "/path/to/project/lib/endpoints/__init__.py", line 28, in <module>
    from apiserving import *
  File "/path/to/project/lib/endpoints/apiserving.py", line 74, in <module>
    from endpoints_management.control import client as control_client
  File "/path/to/project/lib/endpoints_management/__init__.py", line 17, in <module>
    from . import auth, config, control, gen
  File "/path/to/project/lib/endpoints_management/control/__init__.py", line 19, in <module>
    from ..gen import servicecontrol_v1_messages as sc_messages
  File "/path/to/project/lib/endpoints_management/gen/servicecontrol_v1_messages.py", line 23, in <module>
    from apitools.base.py import encoding
  File "/path/to/project/lib/apitools/base/py/__init__.py", line 23, in <module>
    from apitools.base.py.credentials_lib import *
  File "/path/to/project/lib/apitools/base/py/credentials_lib.py", line 50, in <module>
    from oauth2client import locked_file
ImportError: cannot import name locked_file
```

**Comment by inklesspen** [comment]
This is caused by having an incorrect version of oauth2client installed. Endpoints's requirements specification requires compatible versions. You must use oauth2client version 3.0.0; any newer version will not work with apitools.
