### ISSUE TITLE
Getting error in discovery api call

### ISSUE THREAD

**Issue by sagar986** [cloudendpoints/endpoints-python#160]
> "RuntimeError: A tasklet should not yield a plain value"

Here is full traceback.

```
Traceback (most recent call last):
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/7894e0c59273b2b7/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 267, in Handle
    result = handler(dict(self._environ), self._StartResponse)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/7894e0c59273b2b7/python27/python27_lib/versions/1/google/appengine/ext/ndb/tasklets.py", line 1108, in add_context_wrapper
    return synctaskletfunc(*args, **kwds)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/7894e0c59273b2b7/python27/python27_lib/versions/1/google/appengine/ext/ndb/tasklets.py", line 1087, in synctasklet_wrapper
    return taskletfunc(*args, **kwds).get_result()
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/7894e0c59273b2b7/python27/python27_lib/versions/1/google/appengine/ext/ndb/tasklets.py", line 383, in get_result
    self.check_success()
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/7894e0c59273b2b7/python27/python27_lib/versions/1/google/appengine/ext/ndb/tasklets.py", line 378, in check_success
    self.wait()
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/7894e0c59273b2b7/python27/python27_lib/versions/1/google/appengine/ext/ndb/tasklets.py", line 362, in wait
    if not ev.run1():
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/7894e0c59273b2b7/python27/python27_lib/versions/1/google/appengine/ext/ndb/eventloop.py", line 268, in run1
    delay = self.run0()
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/7894e0c59273b2b7/python27/python27_lib/versions/1/google/appengine/ext/ndb/eventloop.py", line 230, in run0
    callback(*args, **kwds)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/7894e0c59273b2b7/python27/python27_lib/versions/1/google/appengine/ext/ndb/tasklets.py", line 509, in _help_tasklet_along
    '%.200s yielded %.200r' % (info, value))
RuntimeError: A tasklet should not yield a plain value: initial generator __call__(endpoints_dispatcher.py:128) yielded '{\n  "auth": {\n    "oauth2": {\n      "scopes": {}\n    }\n  },\n  "basePath": "<APINAME>",\n  "baseUrl": "https://<<PROJECTNAME>>.appspot.com/<APINAME>",\n  "batchPath": "batch"

```
I already tried few things like, i know some of the tries are not logical but though tried.

- Deployment using gcloud and appcfg.py
- Deleted all older version and deploying new version
- Generate new discovery doc and deployed
- Generate openapi service json and deployed new services as well.

Is any one face similar issue pls help me.

**Comment by inklesspen** [comment]
Unfortunately, the ndb library is not fully compatible with the WSGI spec, including with this library. You should report this issue to the maintainers of the ndb library.
