### ISSUE TITLE
After upgrading to 4.8.0, I am not able to generate Library

### ISSUE THREAD

**Issue by zonito** [cloudendpoints/endpoints-python#187]
When I run below command

```sh
python lib/endpoints/endpointscfg.py get_client_lib --output ../PGAPIs/PGAndAPI java -bs gradle api_handler.TestApi --hostname=guru.com
```
I get below error

```
WARNING:root:Could not find either the Cloud SDK or the App Engine Python SDK.
If you encounter errors, please make sure that the SDK binary path is in your
PATH environment variable or that the ENDPOINTS_GAE_SDK variable points to a
valid SDK root.
Traceback (most recent call last):
  File "lib/endpoints/endpointscfg.py", line 27, in <module>
    import _endpointscfg_setup  # pylint: disable=unused-import
  File "/Users/.../project/lib/endpoints/_endpointscfg_setup.py", line 107, in <module>
    _SetupPaths()
  File "/Users/.../project/lib/endpoints/_endpointscfg_setup.py", line 103, in _SetupPaths
    from google.appengine.ext import vendor
ImportError: No module named appengine.ext
```

Here is my requirements.txt

```
dateutils==0.6.6
google-api-python-client==1.7.6
google-endpoints==4.8.0
google-endpoints-api-management==1.11.0
inflect==0.2.5
pre-commit==1.3.0
pycrypto==2.6.1
pylint==1.4.1
```

And when I set `ENDPOINTS_GAE_SDK` to google cloud SDK - then it uses 4.6.1 version.

After requirements.txt, here are list of installed library

```
drwxr-xr-x   9 Zonito  staff     288 Dec 12 06:42 PyYAML-3.13.dist-info
drwxr-xr-x   9 Zonito  staff     288 Dec 12 06:42 WebOb-1.8.4.dist-info
drwxr-xr-x   9 Zonito  staff     288 Dec 12 06:42 argparse-1.4.0.dist-info
drwxr-xr-x   8 Zonito  staff     256 Dec 12 06:42 aspy.yaml-1.1.1.dist-info
drwxr-xr-x   9 Zonito  staff     288 Dec 12 06:42 astroid-1.6.5.dist-info
drwxr-xr-x  10 Zonito  staff     320 Dec 12 06:42 attrs-17.4.0.dist-info
drwxr-xr-x   7 Zonito  staff     224 Dec 12 06:42 backoff-1.7.1.dist-info
drwxr-xr-x  11 Zonito  staff     352 Dec 12 06:42 backports.functools_lru_cache-1.5.dist-info
drwxr-xr-x   7 Zonito  staff     224 Dec 12 06:42 cached_property-1.5.1.dist-info
drwxr-xr-x   9 Zonito  staff     288 Dec 12 06:42 cachetools-1.1.6.dist-info
drwxr-xr-x  10 Zonito  staff     320 Dec 12 06:42 certifi-2018.11.29.dist-info
drwxr-xr-x  10 Zonito  staff     320 Dec 12 06:42 chardet-3.0.4.dist-info
drwxr-xr-x  10 Zonito  staff     320 Dec 12 06:42 dateutils-0.6.6.dist-info
drwxr-xr-x  10 Zonito  staff     320 Dec 12 06:42 dogpile.cache-0.6.8.dist-info
drwxr-xr-x   9 Zonito  staff     288 Dec 12 06:42 enum34-1.1.6.dist-info
drwxr-xr-x   9 Zonito  staff     288 Dec 12 06:42 fasteners-0.14.1.dist-info
drwxr-xr-x  11 Zonito  staff     352 Dec 12 06:42 future-0.17.1.dist-info
drwxr-xr-x   9 Zonito  staff     288 Dec 12 06:42 google_api_python_client-1.7.6.dist-info
drwxr-xr-x   8 Zonito  staff     256 Dec 12 06:42 google_apitools-0.5.25.dist-info
drwxr-xr-x   8 Zonito  staff     256 Dec 12 06:42 google_auth-1.6.1.dist-info
drwxr-xr-x   9 Zonito  staff     288 Dec 12 06:42 google_auth_httplib2-0.0.3.dist-info
drwxr-xr-x   9 Zonito  staff     288 Dec 12 06:42 google_endpoints-4.8.0.dist-info
drwxr-xr-x  10 Zonito  staff     320 Dec 12 06:42 google_endpoints_api_management-1.11.0.dist-info
drwxr-xr-x   9 Zonito  staff     288 Dec 12 06:42 httplib2-0.12.0.dist-info
drwxr-xr-x   8 Zonito  staff     256 Dec 12 06:42 identify-1.1.7.dist-info
drwxr-xr-x   8 Zonito  staff     256 Dec 12 06:42 idna-2.8.dist-info
drwxr-xr-x   9 Zonito  staff     288 Dec 12 06:42 inflect-0.2.5.dist-info
drwxr-xr-x   9 Zonito  staff     288 Dec 12 06:42 lazy_object_proxy-1.3.1.dist-info
drwxr-xr-x  10 Zonito  staff     320 Dec 12 06:42 logilab_common-1.4.2.dist-info
drwxr-xr-x   9 Zonito  staff     288 Dec 12 06:42 monotonic-1.5.dist-info
drwxr-xr-x  10 Zonito  staff     320 Dec 12 06:42 nodeenv-1.3.3.dist-info
drwxr-xr-x   9 Zonito  staff     288 Dec 12 06:42 oauth2client-3.0.0.dist-info
drwxr-xr-x  10 Zonito  staff     320 Dec 12 06:42 pre_commit-1.3.0.dist-info
drwxr-xr-x  11 Zonito  staff     352 Dec 12 06:42 pyasn1-0.4.4.dist-info
drwxr-xr-x  11 Zonito  staff     352 Dec 12 06:42 pyasn1_modules-0.2.2.dist-info
drwxr-xr-x   9 Zonito  staff     288 Dec 12 06:42 pycrypto-2.6.1.dist-info
drwxr-xr-x  10 Zonito  staff     320 Dec 12 06:42 pyjwkest-1.0.9.dist-info
drwxr-xr-x  10 Zonito  staff     320 Dec 12 06:42 pylint-1.4.1.dist-info
drwxr-xr-x   9 Zonito  staff     288 Dec 12 06:42 pylru-1.1.0.dist-info
drwxr-xr-x   9 Zonito  staff     288 Dec 12 06:42 python_dateutil-2.7.5.dist-info
drwxr-xr-x  11 Zonito  staff     352 Dec 12 06:42 pytz-2018.7.dist-info
drwxr-xr-x   8 Zonito  staff     256 Dec 12 06:42 requests-2.21.0.dist-info
drwxr-xr-x  11 Zonito  staff     352 Dec 12 06:42 rsa-4.0.dist-info
drwxr-xr-x  10 Zonito  staff     320 Dec 12 06:42 semver-2.7.7.dist-info
drwxr-xr-x  11 Zonito  staff     352 Dec 12 06:42 setuptools-40.6.3.dist-info
drwxr-xr-x  10 Zonito  staff     320 Dec 12 06:42 singledispatch-3.4.0.3.dist-info
drwxr-xr-x   8 Zonito  staff     256 Dec 12 06:42 six-1.12.0.dist-info
drwxr-xr-x   9 Zonito  staff     288 Dec 12 06:42 strict_rfc3339-0.7.dist-info
drwxr-xr-x   9 Zonito  staff     288 Dec 12 06:42 uritemplate-3.0.0.dist-info
drwxr-xr-x   8 Zonito  staff     256 Dec 12 06:42 urllib3-1.24.1.dist-info
drwxr-xr-x  10 Zonito  staff     320 Dec 12 06:42 virtualenv-16.1.0.dist-info
drwxr-xr-x   9 Zonito  staff     288 Dec 12 06:42 wrapt-1.10.11.dist-info
```

And If it uses 4.6.1 then I get https://github.com/cloudendpoints/endpoints-python/issues/172 issue.

**Comment by inklesspen** [comment]
You say "And when I set ENDPOINTS_GAE_SDK to google cloud SDK - then it uses 4.6.1 version."

But the Google Cloud SDK does not include version 4.6.1 of the Endpoints library. How do you know it is using that version?

You must provide a path to the Google Cloud SDK to use the Endpoints tools, because they require the App Engine SDK libraries.
