### ISSUE TITLE
Endpoints 2.0.0b5 raises exception when loading an _ApiDecorator (instead of a protorpc.remote.Service)

### ISSUE THREAD

**Issue by aetherknight** [cloudendpoints/endpoints-python#27]
I ran into a bug when trying to add an API to endpoints' WSGI application instead of each protorpc service. The following sample application works in endpoints 1, but not in endpoints 2.0.0b5:

main.py:
```python
import endpoints
import protorpc


test_api = endpoints.api(
    name='test',
    version='v1',
    title='Test API',
    allowed_client_ids=[endpoints.API_EXPLORER_CLIENT_ID],
    audiences=[],
    scopes=[endpoints.EMAIL_SCOPE]
)

@test_api.api_class(resource_name='tests', path='tests')
class TestService(protorpc.remote.Service):
    pass


ENDPOINTS_APPLICATION = endpoints.api_server([test_api])
```

Error when main.py is loaded:

```
Traceback (most recent call last):
  File "/Users/wsorvis/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 240, in Handle
    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
  File "/Users/wsorvis/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 299, in _LoadHandler
    handler, path, err = LoadObject(self._handler)
  File "/Users/wsorvis/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 85, in LoadObject
    obj = __import__(path[0])
  File "/Users/wsorvis/src/endpoints2bug/main.py", line 20, in <module>
    ENDPOINTS_APPLICATION = endpoints.api_server([test_api])
  File "/Users/wsorvis/src/endpoints2bug/lib/endpoints/apiserving.py", line 481, in api_server
    apis_app = _ApiServer(api_services, **kwargs)
  File "/Users/wsorvis/src/endpoints2bug/lib/endpoints/apiserving.py", line 239, in __init__
    self.base_paths.add(entry.base_path)
AttributeError: '_ApiServer' object has no attribute 'base_paths'
```

### Root Cause?

`_ApiServer.__init__` in `endpoints/apiserving.py` has a code path that tries to use `self.base_paths` before it is initialized:

```python
  def __init__(self, api_services, **kwargs):
    """... (docstring cut for brevity)"""
    for entry in api_services[:]:
      # pylint: disable=protected-access
      if isinstance(entry, api_config._ApiDecorator):
        api_services.remove(entry)
        api_services.extend(entry.get_api_classes())
        self.base_paths.add(entry.base_path)

    # Record the base paths
    self.base_paths = set()
    for entry in api_services:
      self.base_paths.add(entry.api_info.base_path)

    ...
```

**Comment by bradfriedman** [comment]
Thanks for bringing this up! I'll have a fix in review shortly.

**Comment by bradfriedman** [comment]
This should be fixed now if you update your packages!
